// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '',
    'defaultAlt': '',
    'print': '<pre>{0}</pre>',
    'example:important': '<h1>^2[IMPORTANT] {0}: </h1>'
  },
  fadeTimeout: 7000,
  suggestionLimit: 5,
  style: {
    background: 'rgba(52, 73, 94, 0)',
    width: '25%',
    height: '22%',
  }
};
